name: h1-master

channels: 
    - conda-forge
    - menpo
    - defaults

dependencies:
#  - python=3.11
#  - numpy>=1.23.5
#  - matplotlib>=3.6.2
#  - scipy=1.9.3
#  - pip>=22.3.1
#  - PyWavelets>=1.4.1
#  - tensorflow
#  - ipython
#  - ipykernel
#  - _libgcc_mutex=0.1=main
#  - absl-py=0.12.0
#  - autopep8>=2.0.0
#  - ca-certificates=2021.1.19
#  - cachetools=4.2.1
#  - certifi=2020.12.5
#  - chardet=4.0.0
#  - cycler=0.10.0
#  - cython=0.29.22
#  - decorator=4.4.2
#  - dominate=2.6.0
#  - google-auth=1.28.1
#  - google-auth-oauthlib=0.4.4
#  - grpcio=1.37.0
#  - idna=2.10
#  - imageio=2.9.0
#  - jupyterlab>=3.5.1
#  - kiwisolver=1.3.1
#  - kornia= 0.7.1
#  - ld_impl_linux-64=2.33.1
#  - libsvm>=325
#  - libffi=3.3
#  - libgcc-ng=9.1.0
#  - libstdcxx-ng=9.1.0
#  - markdown=3.3.4
#  - ncurses=6.2
#  - netcdf4
#  - networkx=2.5.1
#  - nbstripout>=0.6.1
#  - oauthlib=3.1.0
#  - opencv=4.6.0
#  - openssl=1.1.1k
#  - pillow=8.2.0
#  - plotly>=5.11.0
#  - protobuf=3.15.8
#  - pyasn1=0.4.8
#  - pyasn1-modules=0.2.8
#  - python-kaleido>=0.2.1
#  - pytorch
 # - pyparsing=2.4.7
 # - python-dateutil=2.8.1
 # - readline=8.1
#  - requests=2.25.1
#  - requests-oauthlib=1.3.0
#  - rsa=4.7.2
#  - scratchai-nightly
#  - setuptools=52.0.0
#  - sewar=0.4.4
#  - six=1.15.0
#  - sqlite=3.35.4
#  - scikit-learn>=1.1.3
#  - scikit-image=0.22.0
#  - spectral>=0.23.1
#  - tensorboard=2.5.0
#  - tensorboard-data-server=0.6.1
#  - tensorboard-plugin-wit=1.8.0
#  - tifffile=2021.4.8
#  - zlib=1.2.11
#  - torch=1.8.1
#  - torchvision=0.9.1
#  - tqdm=4.60.0
#  - typing-extensions=3.7.4.3
#  - tzdata=2020f
#  - urllib3=1.26.4
#  - werkzeug=1.0.1
#  - wheel=0.36.2
#  - xz=5.2.5
#  - tk=8.6.10
#  - xarray



  #- pydensecrf=1.0rc2