name: h1-sharp

channels:
- conda-forge
- menpo
- defaults

dependencies:
  - python==3.11
  - numpy>=1.23.5
  - matplotlib>=3.6.2
  - pandas>=1.5.2
  - scipy>=1.9.3
  - scikit-learn>=1.1.3
  - jupyterlab>=3.5.1
  - scikit-image>=0.19.3 
  - opencv>=4.6.0
  - spectral>=0.23.1
  - autopep8>=2.0.0
  - libsvm>=325
  - pip>=22.3.1
  - libsvm>=325
  - plotly>=5.11.0
  - nbstripout>=0.6.1
  - python-kaleido>=0.2.1
  - PyWavelets>=1.4.1
  - pytorch
  - netcd4
  - xarray